<?php
/*
********************************************************
* @author Santos Montano B. (Lito Santos M.)
* @author_url 1: http://www.kanorika.com
* @author_url 2: http://codecanyon.net/user/kanorika
* @author_email: info@kanorika.com   
********************************************************
* iSocial - Social Networking Platform
* Copyright (c) 2018 iSocial. All rights reserved.
********************************************************
*/
		// Define smiles

		$smiles = array(
			':-)'	=> 'regular.png',
			':)'	=> 'regular.png',
			':-D'	=> 'teeth.png',
			':d'	=> 'teeth.png',
			':D'	=> 'teeth.png',
			':-O'	=> 'omg.png',
			':o'	=> 'omg.png',
			':O'	=> 'omg.png',
			':-P'	=> 'tongue.png',
			':p'	=> 'tongue.png',
			':P'	=> 'tongue.png',
			';-)'	=> 'wink.png',
			';)'	=> 'wink.png',
			':(('	=> 'cry.png',
			':-('	=> 'sad.png',
			':('	=> 'sad.png',
			':-S'	=> 'confused.png',
			':s'	=> 'confused.png',
			':S'	=> 'confused.png',
			':-|'	=> 'what.png',
			':|'	=> 'what.png',
			':-$'	=> 'red.png',
			':$'	=> 'red.png',
			'(H)'	=> 'shades.png',
			'(h)'	=> 'shades.png',
			':-@'	=> 'angry.png',
			':@'	=> 'angry.png',
			'(A)'	=> 'angel.png',
			'(a)'	=> 'angel.png',
			'(6)'	=> 'devil.png',
			':-#'	=> 'dumb.png',
			'8o|'	=> 'growl.png',
			'8-|'	=> 'nerd.png',
			'^o)'	=> 'sarcastic.png',
			':-*'	=> 'secret.png',
			'+o('	=> 'sick.png',
			':^)'	=> 'noknow.png',
			'*-)'	=> 'pensive.png',
			'8-)'	=> 'eyesrolled.png',
			'|-)'	=> 'sleepy.png',
			'(C)'	=> 'coffee.png',
			'(c)'	=> 'coffee.png',
			'(Y)'	=> 'thumbs_up.png',
			'(y)'	=> 'thumbs_up.png',
			'(n)'	=> 'thumbs_down.png',
			'(N)'	=> 'thumbs_down.png',
			'(B)'	=> 'beer_mug.png',
			'(b)'	=> 'beer_mug.png',
			'(D)'	=> 'martini.png',
			'(d)'	=> 'martini.png',
			'(X)'	=> 'girl.png',
			'(x)'	=> 'girl.png',
			'(Z)'	=> 'guy.png',
			'(z)'	=> 'guy.png',
			'({)'	=> 'guy_hug.png',
			'(})'	=> 'girl_hug.png',
			':-['	=> 'bat.png',
			':['	=> 'bat.png',
			'(^)'	=> 'cake.png',
			'(L)'	=> 'heart.png',
			'(l)'	=> 'heart.png',
			'(U)'	=> 'broken_heart.png',
			'(u)'	=> 'broken_heart.png',
			'(K)'	=> 'kiss.png',
			'(k)'	=> 'kiss.png',
			'(G)'	=> 'present.png',
			'(g)'	=> 'present.png',
			'(F)'	=> 'rose.png',
			'(f)'	=> 'rose.png',
			'(W)'	=> 'wilted_rose.png',
			'(w)'	=> 'wilted_rose.png',
			'(p)'	=> 'camera.png',
			'(P)'	=> 'camera.png',
			'(~)'	=> 'film.png',
			'(@)'	=> 'cat.png',
			'(dg)'	=> 'dog.png',
			'(T)'	=> 'phone.png',
			'(t)'	=> 'phone.png',
			'(I)'	=> 'lightbulb.png',
			'(i)'	=> 'lightbulb.png',
			'(8)'	=> 'note.png',
			'(S)'	=> 'moon.png',
			'(*)'	=> 'star.png',
			'(e)'	=> 'envelope.png',
			'(E)'	=> 'envelope.png',
			'(o)'	=> 'clock.png',
			'(O)'	=> 'clock.png',
			'(sn)'	=> 'scargot.png',
			'(pl)'	=> 'dish.png',
			'(||)'	=> 'bowl.png',
			'(pi)'	=> 'pizza.png',
			'(so)'	=> 'ball.png',
			'(au)'	=> 'car.png',
			'(um)'	=> 'umb.png',
			'(ip)'	=> 'isla.png',
			'(co)'	=> 'pc.png',
			'(mp)'	=> 'cel.png',
			'(mo)'	=> 'money.png',
		);